Repository LikeLion-13th-SKHU/LikeLion-13th-TEAM06-BE, pull requests merged in 2025-08, with the labels that each got.

#6 feat: 소셜로그인 기능구현 카카오/구글/네ì이버 #5
  DongneRing/.gitignore
  DongneRing/build.gradle
  DongneRing/src/main/java/com/dongnering/common/error/ErrorCode.java
  DongneRing/src/main/java/com/dongnering/common/error/SuccessCode.java
  DongneRing/src/main/java/com/dongnering/global/config/SecurityConfig.java
  DongneRing/src/main/java/com/dongnering/global/jwt/JwtAuthorizationFilter.java
  DongneRing/src/main/java/com/dongnering/global/jwt/JwtTokenProvider.java
  DongneRing/src/main/java/com/dongnering/mypage/api/MemberController.java
  DongneRing/src/main/java/com/dongnering/mypage/api/dto/request/MemberJoinReqDto.java
  DongneRing/src/main/java/com/dongnering/mypage/api/dto/request/MemberLoginReqDto.java
  DongneRing/src/main/java/com/dongnering/mypage/api/dto/response/MemberInfoResDto.java
  DongneRing/src/main/java/com/dongnering/mypage/application/MypageService.java
  DongneRing/src/main/java/com/dongnering/mypage/domain/Member.java
  DongneRing/src/main/java/com/dongnering/mypage/domain/Role.java
  DongneRing/src/main/java/com/dongnering/mypage/domain/repository/MemberRepository.java
  DongneRing/src/main/java/com/dongnering/oauth2/google/api/GoogleOAuthController.java
  DongneRing/src/main/java/com/dongnering/oauth2/google/api/dto/GoogleTokenResponse.java
  DongneRing/src/main/java/com/dongnering/oauth2/google/api/dto/GoogleUserInfo.java
  DongneRing/src/main/java/com/dongnering/oauth2/google/application/GoogleOAuthService.java
  DongneRing/src/main/java/com/dongnering/oauth2/kakao/api/KakaoOAuthController.java
  DongneRing/src/main/java/com/dongnering/oauth2/kakao/api/dto/KakaoTokenResponse.java
  DongneRing/src/main/java/com/dongnering/oauth2/kakao/api/dto/KakaoUserInfo.java
  DongneRing/src/main/java/com/dongnering/oauth2/kakao/application/KakaoOAuthService.java
  DongneRing/src/main/java/com/dongnering/oauth2/naver/api/NaverOAuthController.java
  DongneRing/src/main/java/com/dongnering/oauth2/naver/api/dto/NaverTokenResponse.java
  DongneRing/src/main/java/com/dongnering/oauth2/naver/api/dto/NaverUserInfo.java
  DongneRing/src/main/java/com/dongnering/oauth2/naver/application/NaverOAuthService.java
  DongneRing/src/main/resources/application-oauth.yml
  DongneRing/src/main/resources/application.yml
Labels: Feature

#10 [Feat/#9] - RefreshToken 기능 구현
  DongneRing/src/main/java/com/dongnering/art/application/ArtService.java
  DongneRing/src/main/java/com/dongnering/comment/newsComment/application/NewsCommentService.java
  DongneRing/src/main/java/com/dongnering/comment/newsComment/domain/NewsComment.java
  DongneRing/src/main/java/com/dongnering/comment/newsComment/domain/repository/NewsCommentRepository.java
  DongneRing/src/main/java/com/dongnering/global/jwt/JwtAuthorizationFilter.java
  DongneRing/src/main/java/com/dongnering/global/jwt/JwtTokenProvider.java
  DongneRing/src/main/java/com/dongnering/global/jwt/TokenResDto.java
  DongneRing/src/main/java/com/dongnering/member/api/MemberController.java
  DongneRing/src/main/java/com/dongnering/member/api/dto/request/MemberJoinReqDto.java
  DongneRing/src/main/java/com/dongnering/member/api/dto/request/MemberLoginReqDto.java
  DongneRing/src/main/java/com/dongnering/member/api/dto/response/MemberInfoResDto.java
  DongneRing/src/main/java/com/dongnering/member/application/MemberService.java
  DongneRing/src/main/java/com/dongnering/member/domain/Member.java
  DongneRing/src/main/java/com/dongnering/member/domain/Role.java
  DongneRing/src/main/java/com/dongnering/member/domain/repository/MemberRepository.java
  DongneRing/src/main/java/com/dongnering/memberArtLike/MemberArtLike.java
  DongneRing/src/main/java/com/dongnering/memberArtLike/MemberArtLikeRepository.java
  DongneRing/src/main/java/com/dongnering/memberInterest/domain/MemberInterest.java
  DongneRing/src/main/java/com/dongnering/memberNewsLike/MemberNewsLike.java
  DongneRing/src/main/java/com/dongnering/memberNewsLike/MemberNewsLikeRepository.java
  DongneRing/src/main/java/com/dongnering/mypage/api/MemberController.java
  DongneRing/src/main/java/com/dongnering/mypage/api/dto/request/MemberLoginReqDto.java
  DongneRing/src/main/java/com/dongnering/mypage/application/MypageService.java
  DongneRing/src/main/java/com/dongnering/news/application/NewsService.java
  DongneRing/src/main/java/com/dongnering/oauth2/OauthController.java
  DongneRing/src/main/java/com/dongnering/oauth2/OauthService.java
  DongneRing/src/main/java/com/dongnering/oauth2/common/application/LoginFirstAdditionalInfoService.java
  DongneRing/src/main/java/com/dongnering/oauth2/google/api/GoogleOAuthController.java
  DongneRing/src/main/java/com/dongnering/oauth2/google/application/GoogleOAuthService.java
  DongneRing/src/main/java/com/dongnering/oauth2/kakao/api/KakaoOAuthController.java
  DongneRing/src/main/java/com/dongnering/oauth2/kakao/application/KakaoOAuthService.java
  DongneRing/src/main/java/com/dongnering/oauth2/naver/api/NaverOAuthController.java
  DongneRing/src/main/java/com/dongnering/oauth2/naver/application/NaverOAuthService.java
  DongneRing/src/main/resources/application-oauth.yml
Labels: Feature

#27 [Refactor/#24] - 개인화 여부 응답에 추가
  DongneRing/src/main/java/com/dongnering/global/jwt/TokenResDto.java
  DongneRing/src/main/java/com/dongnering/member/api/dto/request/MemberSaveReqDto.java
  DongneRing/src/main/java/com/dongnering/member/application/MemberService.java
  DongneRing/src/main/java/com/dongnering/member/domain/Member.java
  DongneRing/src/main/java/com/dongnering/oauth2/OauthService.java
Labels: Refactor

#29 [Refactor/#24] - 뉴스 단건 조회시 태그 리스트 전달
  DongneRing/src/main/java/com/dongnering/configuration/News/NewsInitializerWithAiServer.java
  DongneRing/src/main/java/com/dongnering/configuration/art/ArtInitializer.java
  DongneRing/src/main/java/com/dongnering/news/api/dto/response/NewsSingleByIdDto.java
Labels: Refactor

#30 [Refactor/#24] - mypage 코드 추가
  DongneRing/src/main/java/com/dongnering/member/api/MemberController.java
  DongneRing/src/main/java/com/dongnering/member/api/dto/request/MemberInterestUpdateReqDto.java
  DongneRing/src/main/java/com/dongnering/member/api/dto/request/MemberProfileUpdateReqDto.java
  DongneRing/src/main/java/com/dongnering/member/api/dto/request/MemberUpdateReqDto.java
  DongneRing/src/main/java/com/dongnering/member/application/MemberService.java
  DongneRing/src/main/java/com/dongnering/member/domain/Member.java
  DongneRing/src/main/java/com/dongnering/memberInterest/domain/repository/MemberInterestRepository.java
Labels: Refactor

#31 [Chore/#13] - yml db setting update
  DongneRing/src/main/resources/application.yml
Labels: Task

#36 [Refactor/#20] - birthday info 응답에 추가
  DongneRing/src/main/java/com/dongnering/member/api/dto/response/MemberInfoResDto.java
  DongneRing/src/main/java/com/dongnering/member/application/MemberService.java
Labels: Refactor

#37 [Refactor/#11] - emailSender
  DongneRing/src/main/java/com/dongnering/DongneRingApplication.java
  DongneRing/src/main/java/com/dongnering/mail/scheduler/NewsScheduler.java
Labels: Refactor

#39 [Refactor/#20] - birthDate 추가
  DongneRing/src/main/java/com/dongnering/member/api/dto/request/MemberInterestUpdateReqDto.java
  DongneRing/src/main/java/com/dongnering/member/domain/Member.java
  DongneRing/src/main/java/com/dongnering/oauth2/google/application/GoogleOAuthService.java
  DongneRing/src/main/resources/application.yml
Labels: Refactor

#41 [Fix/#20] - 중복 코드 제거 및 개인화 상태 업데이트
  DongneRing/src/main/java/com/dongnering/member/application/MemberService.java
  DongneRing/src/main/java/com/dongnering/member/domain/Member.java
Labels: Bug, Fix
